name = "cloudocs"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "DOCS", id = "bafaf13435d348f59e9aa2b8917ac339" }
]

[dev]
port = 8787

[site]
bucket = "./public"

[[routes]]
pattern = "docs.wangzhen.cc"
custom_domain = true 

[observability.logs]
enabled = true